set("DEPENDS_ON_PACKAGES" "xproto" CACHE INTERNAL "")
set("DEPENDS_ON_PACKAGES" "${DEPENDS_ON_PACKAGES}" "xextproto" CACHE INTERNAL "")
set("DEPENDS_ON_PACKAGES" "${DEPENDS_ON_PACKAGES}" "x11" CACHE INTERNAL "")
set("PKGCONFIG_EXPORT_TARGETS" "xext" CACHE INTERNAL "")
