set("JAS_ENABLE_AUTOMATIC_DEPENDENCIES" "OFF" CACHE INTERNAL "")
set("JAS_ENABLE_OPENGL" "OFF" CACHE INTERNAL "")
set("JAS_ENABLE_PROGRAMS" "OFF" CACHE INTERNAL "")
set("JAS_ENABLE_DOC" "OFF" CACHE INTERNAL "")
