set("BUILD_METIS" "YES" CACHE INTERNAL "")
set("WITH_OPENBLAS" "YES" CACHE INTERNAL "")
set("METIS_IDXTYPEWIDTH" "32" CACHE INTERNAL "")
set("HUNTER_INSTALL_LICENSE_FILES" "LICENSE.md" CACHE INTERNAL "")
