set("CMAKE_Fortran_COMPILER" "NOTFOUND" CACHE INTERNAL "")
set("BUILD_TESTING" "OFF" CACHE INTERNAL "")
set("EIGEN_BUILD_DOC" "OFF" CACHE INTERNAL "")
set("HUNTER_INSTALL_LICENSE_FILES" "COPYING.MPL2" CACHE INTERNAL "")
