set("LIBDEFLATE_BUILD_STATIC_LIB" "YES" CACHE INTERNAL "")
set("LIBDEFLATE_BUILD_SHARED_LIB" "NO" CACHE INTERNAL "")
set("LIBDEFLATE_USE_SHARED_LIB" "NO" CACHE INTERNAL "")
set("LIBDEFLATE_BUILD_TESTS" "NO" CACHE INTERNAL "")
